combinators:
	sep --file=combinators.sep

CeilingDivision:
	sep --file=CeilingDivision.sep

ZipN:
	sep --file=ZipN.sep

fullbintree:
	sep --file=fullbintree.sep

Vectors:
	sep --file=Vectors.sep

ParseTest:
	sep --file=ParseTest.sepp