Arithmetic:	Arithmetic.trellys
	trellys -t Arithmetic.trellys

typetest:	typetest.trellys
	trellys -t typetest.trellys

Vectors:	Vectors.trellys
	trellys -t Vectors.trellys

Append2:	Append2.trellys
	trellys -t Append2.trellys