Set respect_strategies

Fix nat : * = 
        self n . ! C : (nat => *) . (! n : nat. (C (succ n))) -> (C zero) -> 
                   (C conv n to nat by refl, unfold) 
    ,
    zero : nat = 
         conv \ C : nat => * . \ s : (! n : nat. (C (succ n))) . \ z : (C zero) . z 
         to nat 
         by (! C : refl . (! s : refl . (! z : refl . (C unfold)))),
            [ unfold ; substself ]
           
    ,
    succ : nat -> nat = 
         \ n : nat . 
           conv \ C : nat => * . \ s : (! n : nat. (C (succ n))) . \ z : (C zero) . (s n) 
           to nat
           by ( ! C : refl . refl -> refl -> (C [ (unfold refl) ; eval ])) ,
              [ unfold ; substself ]

Define nat_elim : ! n : nat . 
                  ! C : (nat => *) . 
                  (! n : nat. (C (succ n))) -> 
                  (C zero) -> 
                  (C n) =
  \ n : nat .
  (conv n to ! C : (nat => *) . (! n : nat. (C (succ n))) -> (C zero) -> (C n) 
             by [ unfold ; substself ] , refl)

Fix add : nat -> nat -> nat =
    \ n : nat . \ m : nat .
       (conv
          (nat_elim n
            (\ n :: nat . nat))
         to ((nat -> nat) -> nat -> nat)
         by ((refl -> [ (refl (unfold refl)); eval]) -> eval -> eval), refl
         (\ p : nat . (succ (add p m))) 
         m)

Fix eq : ! A : *. A => A => * = 
         \ A : * . \ a :: A . \ b :: A . 
           self p. ! C : (! b :: A . (eq A a b) => *) .
           (C a (eqrefl A a)) ->
           (C b conv p to (eq A a b) by refl , [ (unfold A a b) ; eval ] )
      ,
      eqrefl : ! A : * . ! a :: A . (eq A a a) = 
         \ A : * . \ a :: A .
         conv
         \ C : (! b :: A. (eq A a b) => *) .
         \ p : (C a (eqrefl A a)). p
         to (eq A a a)
         by (! C : refl . ! p : refl . (C a [ (unfold A a) ; eval ])) , [ (unfold A a a) ; eval ; substself ]

# This eqconv is for the common case where we want to eliminate over a predicate C which
# depends only on the RHS of the equality, not the equality proof itself.

Define eqconv : ! A : *. ! a :: A . ! b :: A . ! C : (A => *) . (C a) -> (eq A a b) -> (C b) =
  \ A : *. \ a :: A. \ b :: A . \ C : A => * . \ u : (C a) . \ p : (eq A a b) .
    conv
      ((conv p to (! C : (! b :: A . (eq A a b) => *) .
                  (C a (eqrefl A a)) -> 
                  (C b p))
              by [ (unfold A a b) ; eval ; substself ] , refl)
       (\ x :: A . \ u :: (eq A a x) . (C x))
       conv u 
       to ((\ x :: A . (\ u :: (eq A a x) . (C x))) a (eqrefl A a))
       by refl, eval)
     to (C b)
     by eval, refl

Define terminates : ! A : *. A => * =
    \ A : *. \ a :: A .
     ! C : (A  => *). 
       (! a :: A. ! v : A . (eq A a v) -> (C a)) -> 
       (C a)

Define valax : ! A : *. ! a : A . (terminates A a) =
  \ A : * . \ a : A .
  conv \ C : (A => *).
       \ u : (! a :: A. ! v : A . (eq A a v) -> (C a)). (u a a (eqrefl A a))
  to (terminates A a)
  by refl , [ (unfold A a) ; eval ]

