all:	encode lists church

church:
	../subcore church.sub

terminates:
	../subcore terminates.sub

arity-gen:
	../subcore arity-gen.sub

lam:
	../subcore lam.sub

encode:
	../subcore encode.sub

lists:
	../subcore lists.sub